RoleConverter added as a solution for:
Failed to convert property value of type java.lang.String to required
type java.util.Set for property roles; nested exception is
java.lang.IllegalStateException: Cannot convert value of type
java.lang.String to required type com.acp7.springacp7cloud.entity.Role
for property roles[0]: no matching editors or conversion strategy found